version: '3'


services:
  weshopimage:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./ecommerceWebSite:/ecommerce_app
    env_file:
      - ./ecommerceWebSite/core/.env
    ports:
      - 8000:8000
    command: python3 manage.py runserver --settings=core.base.test 0.0.0.0:8000
  postgres:
    image: postgres:9.6.18-alpine
    env_file:
      - ./ecommerceWebSite/core/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: