# Generated by Django 3.0 on 2020-05-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weShop', '0002_orderitem_datedecreation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
    ]
