# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-26 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weShop', '0002_auto_20200425_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=30)),
                ('lname', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(max_length=30)),
                ('message', models.TextField(max_length=30)),
            ],
        ),
    ]
