# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-09 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weShop', '0002_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='icon',
        ),
    ]
