# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weShop', '0002_product_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='weShop.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='weShop.Size'),
        ),
    ]
