# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weShop', '0003_auto_20200509_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
