# Generated by Django 3.0 on 2020-06-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weShop', '0004_auto_20200611_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fNmae',
            new_name='fName',
        ),
    ]
