# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weShop', '0004_product_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
