# Generated by Django 3.0 on 2020-05-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weShop', '0005_auto_20200510_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='upload/categorys/children.jpg', upload_to='categorys/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='upload/'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quntity', models.IntegerField(default=1)),
                ('total', models.FloatField()),
                ('product', models.ManyToManyField(to='weShop.Product')),
            ],
        ),
    ]
