# Generated by Django 3.0 on 2020-06-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weShop', '0010_order_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lname',
        ),
        migrations.AddField(
            model_name='contact',
            name='firstname',
            field=models.CharField(default='omar', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='lastname',
            field=models.CharField(default='omar', max_length=30),
            preserve_default=False,
        ),
    ]
