# Generated by Django 2.2.13 on 2020-06-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weShop', '0014_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
