# Generated by Django 2.2.13 on 2020-08-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weShop', '0015_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_de',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='summary_de',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='summary_en',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
